# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1
[es]
languageName = "Espa√±ol"
languagedirection = "ltr"
title = "Example Site"
weight = 0
